"""add block_logs table

Revision ID: 1de0891f21c8
Revises: 6c8b80a5540a
Create Date: 2025-09-24 11:44:08.261293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de0891f21c8'
down_revision = '6c8b80a5540a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('risk', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('applied_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('block_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_logs_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_block_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_block_logs_ip'))

    op.drop_table('block_logs')
    # ### end Alembic commands ###
